baseurl: ""
url: "http://club.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
yandex_metrika: 38294550
google_analytics: UA-46456269-14
permalink: /:title/

title: "Клуб личностного роста Николая Воробьева"
description: "Клуб — это инструмент, который помогает добиваться больших результатов с помощью развития личных качеств"
keywords: "Клуб личностного роста"
author: "Николай Воробьёв"
vk_app_id: 5534188
#vk_app_id: 4569992 # 127.0.0.1

collections:
  pages-live:
    output: true
    permalink: /live/:path/

defaults:
  - scope:
      path: ""
      type: pages-live
    values:
      layout: live

# Компилируйся!